### ISSUE TITLE
fatal build error: missing DistanceMatrix.hpp

### ISSUE THREAD

**Issue by lneaves** [pranjalv123/ASTRID#1]
Hello, 
Following the instructions to build ASTRID2 but build terminated saying the DistanceMatrix.hpp did not exist. Details below. Any ideas on what went wrong? Thanks

user@tobyg2:~/ASTRID/build$ cmake ../src
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Java: /usr/lib/jvm/java-11-oracle/bin/java (found version "11.0.2")
-- Found JNI: /usr/lib/jvm/java-11-oracle/lib/libjawt.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/ASTRID/build
user@tobyg2:~/ASTRID/build$ make
Scanning dependencies of target Test
[  1%] Building CXX object CMakeFiles/Test.dir/FastMEInterface.cpp.o
In file included from /home/linda_n/ASTRID/src/FastMEInterface.cpp:1:0:
/home/user/ASTRID/src/DistanceMethods.hpp:8:10: fatal error: DistanceMatrix.hpp: No such file or directory
 #include <DistanceMatrix.hpp>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
CMakeFiles/Test.dir/build.make:62: recipe for target 'CMakeFiles/Test.dir/FastMEInterface.cpp.o' failed
make[2]: *** [CMakeFiles/Test.dir/FastMEInterface.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Test.dir/all' failed
make[1]: *** [CMakeFiles/Test.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
user@tobyg2:~/ASTRID/build$

**Comment by Kevin-Ziegler** [comment]
I get the same error!

**Comment by theo-llewellyn** [comment]
same here

**Comment by pschafran** [comment]
Same

**Comment by milag6** [comment]
Yes, same

**Comment by pranjalv123** [comment]
Sorry for the long delay getting this fixed - I've updated the build system to (hopefully) get rid of these dependency issues, and precompiled executables are now automatically generated at each commit and are available at https://github.com/pranjalv123/ASTRID/releases.
