### ISSUE TITLE
Crash with free() invalid: size()

### ISSUE THREAD

**Issue by BenoitMorel** [pranjalv123/ASTRID#14]
Dear Pranjal,

I have successfully installed Astrid with the bazel system as explained in the README.

When I run it, I get the following error:
``` 
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0923 15:09:48.831423 24464 astrid.cpp:144] Reading trees...
I0923 15:09:48.831540 24464 astrid.cpp:150] Read 1 trees
Estimating tree
Running upgma
free(): invalid size
Aborted (core dumped)
``` 

I reproduce with any input tree(s). For instance:
``` 
../ASTRID/bazel-bin/src/ASTRID -i gene_trees.txt  -o output.newick
``` 
with gene_trees.txt containing:
```
((a,b),(c,d));
```

It looks like ASTRID manages to output a tree (in `output.newick.1`) but I don't know if this is the final tree.
I reproduced this on both ubuntu and centos.

I also get an issue (but maybe it's related to the invalid free problem) when running bionj, and in this case, I don't get any output tree at all:
```
../ASTRID/bazel-bin/src/ASTRID-phydstar -i gene_trees.txt  -o output.newick --bionj
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0923 15:18:33.230427 100869 astrid.cpp:144] Reading trees...
I0923 15:18:33.230530 100869 astrid.cpp:150] Read 1 trees
Estimating tree
Running bionj
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f986e13c4ff, pid=100869, tid=0x00007f98737347c0
#
# JRE version: OpenJDK Runtime Environment (8.0_272-b10) (build 1.8.0_272-b10)
# Java VM: OpenJDK 64-Bit Server VM (25.272-b10 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x7024ff]  get_method_id(JNIEnv_*, _jclass*, char const*, char const*, bool, Thread*) [clone .isra.196]+0x8f
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /data/morelbt/github/phd_experiments/hs_err_pid100869.log
#
# If you would like to submit a bug report, please visit:
#   https://bugzilla.redhat.com/enter_bug.cgi?product=Red%20Hat%20Enterprise%20Linux%207&component=java-1.8.0-openjdk
#
Aborted
```

I hope you can help!

Best,
Benoit

**Comment by BenoitMorel** [comment]
This line seems to be wrong, removing it seems to solve the first issue.

https://github.com/pranjalv123/ASTRID/blob/master/src/astrid.cpp#L223


But I still get the JAVA issue with bionj

**Comment by BenoitMorel** [comment]
Regarding the JAVA issue, I found a bypass. 
The path here: https://github.com/pranjalv123/ASTRID/blob/master/src/DistanceMethods/phydstar.cpp#L45
is equal to
```
-Djava.class.path=/home/morelbt/.cache/bazel/_bazel_morelbt/5122b0a35d387e2057fb5506aa127b06/execroot/__main__/bazel-out/k8-opt/bin/src/PhyDstar.jar
```
The corresponding directory exists, but the jar file does not exist. I copied it from ASTRID/third_party/PhyDstar/PhyDstar.jar and it seems to work.

I don't know if something went wrong during the installation...

**Comment by pranjalv123** [comment]
Hi Benoit,

I'm glad you were able to get it to work. I no longer recommend using PhyD* with ASTRID, partially because it gives worse results, and partially because it is difficult to configure properly.

The default ASTRID configuration should work with incomplete distance matrices and give you better results than you get with PhyD*.

**Comment by BenoitMorel** [comment]
Great, thanks for the advice :-)
