### ISSUE TITLE
Error message in latest Mac OS X release

### ISSUE THREAD

**Issue by ekmolloy** [pranjalv123/ASTRID#16]
Hi Pranjal,

Just letting you know that I get the following error in the latest release

ASTRID-macos(42463,0x1195c1e00) malloc: *** error for object 0x7ffee3cd2af8: pointer being freed was not allocated
ASTRID-macos(42463,0x1195c1e00) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

but it hasn't impacted me using ASTRID (the output files are written before the error occurs).

Also, it looks like UPGMA is the default method now? My output was
```
Estimating tree
Running upgma
```
but if I include the -s flag, then the output was
```
Estimating tree
Running fastme_spr

 . Performing NNI...

 . Performing SPR...
```

None of this is urgent, just letting you know.

Thanks!
-Erin

**Comment by pranjalv123** [comment]
Should be fixed now - it runs UPGMA, then SPR (but it was crashing after
UPGMA because of a memory bug).

**Comment by pranjalv123** [comment]
Also, if you were running it without options (i.e. it was crashing after
UPGMA), you should redo those runs, since it wasn't actually doing SPR.

**Comment by ekmolloy** [comment]
It works - thanks!
