### ISSUE TITLE
Problem with bazel build //src:ASTRID-phydstar -c opt

### ISSUE THREAD

**Issue by Gefsy** [pranjalv123/ASTRID#3]
hi, it's my first time to use ASTRID. I bazel build //src:ASTRID -c opt successful, but i cannot bazel build //src:ASTRID-phydstar -c opt.
Thanks for any help.

[Untitled Document 1.txt](https://github.com/pranjalv123/ASTRID/files/6108100/Untitled.Document.1.txt)

**Comment by pranjalv123** [comment]
I think this is fixed in the newest version of ASTRID. You might still have errors depending on how your java environment is set up. I can try and help figure them out if you do.

**Comment by jsdoublel** [comment]
I'm having a similar problem using `bazel build //src:ASTRID-phydstar -c opt` with the most recent version of ASTRID. It's failing giving the following error:

```
ERROR: /home/jamessw3/software/ASTRID/src/BUILD:3:10: Linking of rule '//src:ASTRID-phydstar' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/src/ASTRID-phydstar-2.params

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc @bazel-out/k8-opt/bin/src/ASTRID-phydstar-2.params

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-opt/bin/_solib_k8/_U_S_Ssrc_CASTRID-phydstar___Ulocal_Ujdk_Sjre_Slib_Samd64/libdeploy.so: error: undefined reference to 'jws_g_list_length'
bazel-out/k8-opt/bin/_solib_k8/_U_S_Ssrc_CASTRID-phydstar___Ulocal_Ujdk_Sjre_Slib_Samd64/libdeploy.so: error: undefined reference to 'jws_g_list_nth_data'
bazel-out/k8-opt/bin/_solib_k8/_U_S_Ssrc_CASTRID-phydstar___Ulocal_Ujdk_Sjre_Slib_Samd64/libdeploy.so: error: undefined reference to 'native_trace'
bazel-out/k8-opt/bin/_solib_k8/_U_S_Ssrc_CASTRID-phydstar___Ulocal_Ujdk_Sjre_Slib_Samd64/libnpjp2.so: error: undefined reference to 'std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)'
bazel-out/k8-opt/bin/src/DistanceMethods/_objs/PhyDStar/phydstar.o:phydstar.cpp:function BioNJStar(TaxonSet&, DistanceMatrix&, std::vector<std::string, std::allocator<std::string> >&): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
collect2: error: ld returned 1 exit status
Target //src:ASTRID-phydstar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 18.142s, Critical Path: 10.18s
INFO: 16 processes: 3 internal, 13 processwrapper-sandbox.
FAILED: Build did NOT complete successfully
```

Let me know if there's any other information that would be helpful. Thanks!

**Comment by pranjalv123** [comment]
This is the java compilation error I referred to in my last comment. You might try ensuring you have the java developer kit installed. However, are you sure you want to use phydstar? The procedure that ASTRID will suggest if you give it a dataset with missing elements is far superior.

**Comment by pranjalv123** [comment]
The command for that would be like

ASTRID -i <input gene trees> -o <output species tree> -u -n -s


You could also use the new --cache option which writes the distance matrix to a file in Phylip format, and run phyd* manually on that.

**Comment by jsdoublel** [comment]
I'll look into both of those options. Thanks!
