### ISSUE TITLE
Switching the default method for missing data to `-u -s` or `-u -n -s`

### ISSUE THREAD

**Issue by RuneBlaze** [pranjalv123/ASTRID#4]
I am following up from a previous correspondence from Dr. Warnow's lab. As shown in your thesis, `-u -s` is superior to BioNJ*, so it would be great for either `-u -s` or `-u -n -s` to be made the default arguments when missing data is seen

(Of course, let me know if this is how you want me to create the issues, or even if you think I should best do some parts of it. I don't know how simple some of these things are, and whether you prefer pull requests filled with potential C++ novice mistakes over modifying on your own. I can also just maintain a fork if you feel like some of the features are out of scope).

**Comment by pranjalv123** [comment]
Thanks for creating this issue. I am happy to make changes if you make issues, and I am also happy to review and accept pull requests. I would prefer it if this was the "canonical" version of ASTRID; while you are certainly free to maintain your own fork, I think it's easier for users if all the features are in one place.

**Comment by pranjalv123** [comment]
Fixed by PR #7

**Comment by pranjalv123** [comment]
(also, I try to respond to pull requests ASAP. For issues it depends when I have time to dig into them.)
