### ISSUE TITLE
`-u -n -s`, difference from `-u -s`

### ISSUE THREAD

**Issue by RuneBlaze** [pranjalv123/ASTRID#6]
https://github.com/pranjalv123/ASTRID/blob/a0ad47174921f3cc37c47a802f48255858ae3716/src/astrid.cpp#L111-L124

From what I gathered, ASTRID does fill in of the matrix using this `fill_in` function. What I am confused about is that this `fill_in` seems to be a NOP after called once on the distance matrix. Lines 119 to 120 will only be run (the only place where this function modifies `dm`) if `!dm.has(i,j)`, which is equivalent to saying (inside the instance of `dm`) `get(i, j, mask_) != 0;`. Line 120 will modify the matrix to have mask at taxon i, j to be 1. Therefore each entry, in the process of being filled, will never be filled again in the future.

This seems to imply that `-u -n -s` is the same as `-u -s`, since `dm` is already been filled out (all mask values != 0) when FastME-NNI is run, and the resulting tree is never used (since `dm` has already been filled out), and `FastME` itself seems like a pure function (never modifies `dm`. It only outputs a tree). Therefore the second iteration, under this logic, is not useful in any way. There should be somewhere where my reasoning is wrong (or else `-u -n -s` is the same as `-u -s`), but where?

**Comment by pranjalv123** [comment]
Yes, I think you're right. That might explain why multiple iterations didn't have any effect. I'll fix this, and it would be worth testing again.
